apply from: "$rootProject.projectDir/gradle/config/dependencies.gradle"

dependencies {
    implementation project.parent.project("domain")

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.modulith:spring-modulith-starter-jpa'
    implementation 'org.springframework.modulith:spring-modulith-events-kafka'

    // RabbitMQ alternative (use this instead of the Kafka externalizer):
    // implementation 'org.springframework.modulith:spring-modulith-events-amqp'
    // implementation 'org.springframework.boot:spring-boot-starter-amqp'

    implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap'

    implementation 'com.zaxxer:HikariCP'
    implementation 'javax.xml.bind:jaxb-api'
    implementation 'com.sun.xml.bind:jaxb-impl'
    implementation 'com.sun.xml.bind:jaxb-core'
    implementation 'com.sun.xml.bind:jaxb-osgi'
    implementation 'com.mysql:mysql-connector-j'
    implementation 'org.projectlombok:lombok'

    annotationProcessor 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'com.h2database:h2'
}

test {
    useJUnitPlatform()
}
