import org.springframework.boot.gradle.tasks.bundling.BootJar

description = 'Shipping Api'
jar.archiveBaseName = 'shipping-api'

apply plugin: 'org.springframework.boot'

dependencies {
    implementation project('infra')
}

springBoot {
    mainClass = 'com.yolla.shippingapi.ShippingApiApplication'
}

bootRun {
    if (project.hasProperty('args')) {
        args project.args.split(',')
    }
    if (project.hasProperty('jvmArgs')) {
        jvmArgs = project.jvmArgs.split(',') as List
    }
}

tasks.withType(BootJar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}